<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo: 2 Definición del Modelo ARIMA | Analisis Tasa de Intervencion</title>
  <meta name="description" content="Capítulo: 2 Definición del Modelo ARIMA | Analisis Tasa de Intervencion" />
  <meta name="generator" content="bookdown 0.41 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo: 2 Definición del Modelo ARIMA | Analisis Tasa de Intervencion" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo: 2 Definición del Modelo ARIMA | Analisis Tasa de Intervencion" />
  
  
  

<meta name="author" content="Gabriel Orozco/Diana Aguirre/Edgard Camacho" />


<meta name="date" content="2024-10-21" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="enunciado.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Analisis Tasa de Intervencion</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="enunciado.html"><a href="enunciado.html"><i class="fa fa-check"></i><b>1</b> <strong>Enunciado</strong></a>
<ul>
<li class="chapter" data-level="1.1" data-path="enunciado.html"><a href="enunciado.html#análisis-exploratorio"><i class="fa fa-check"></i><b>1.1</b> Análisis exploratorio</a></li>
<li class="chapter" data-level="1.2" data-path="enunciado.html"><a href="enunciado.html#gráficos-de-visualización"><i class="fa fa-check"></i><b>1.2</b> Gráficos de visualización</a></li>
<li class="chapter" data-level="1.3" data-path="enunciado.html"><a href="enunciado.html#análisis-de-serie-de-tiempo"><i class="fa fa-check"></i><b>1.3</b> Análisis de serie de tiempo</a></li>
<li class="chapter" data-level="1.4" data-path="enunciado.html"><a href="enunciado.html#promedio-o-media-móvil"><i class="fa fa-check"></i><b>1.4</b> Promedio o media móvil</a></li>
<li class="chapter" data-level="1.5" data-path="enunciado.html"><a href="enunciado.html#rezago-operador-backshift-y-estacionalidad"><i class="fa fa-check"></i><b>1.5</b> Rezago (operador backshift) y estacionalidad</a></li>
<li class="chapter" data-level="1.6" data-path="enunciado.html"><a href="enunciado.html#descomposición"><i class="fa fa-check"></i><b>1.6</b> Descomposición</a></li>
<li class="chapter" data-level="1.7" data-path="enunciado.html"><a href="enunciado.html#estacionariedad"><i class="fa fa-check"></i><b>1.7</b> Estacionariedad</a></li>
<li class="chapter" data-level="1.8" data-path="enunciado.html"><a href="enunciado.html#diferenciación"><i class="fa fa-check"></i><b>1.8</b> Diferenciación</a></li>
<li class="chapter" data-level="1.9" data-path="enunciado.html"><a href="enunciado.html#volver-a-verificar-la-estacionariedad-tras-la-diferenciación"><i class="fa fa-check"></i><b>1.9</b> Volver a verificar la Estacionariedad tras la Diferenciación</a></li>
<li class="chapter" data-level="1.10" data-path="enunciado.html"><a href="enunciado.html#autocorrelación-acf-y-parcial-pacf"><i class="fa fa-check"></i><b>1.10</b> Autocorrelación (ACF) y Parcial (PACF)</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="definición-del-modelo-arima.html"><a href="definición-del-modelo-arima.html"><i class="fa fa-check"></i><b>2</b> <strong>Definición del Modelo ARIMA</strong></a>
<ul>
<li class="chapter" data-level="2.1" data-path="definición-del-modelo-arima.html"><a href="definición-del-modelo-arima.html#algoritmo-de-holt-winter"><i class="fa fa-check"></i><b>2.1</b> Algoritmo de Holt Winter</a></li>
<li class="chapter" data-level="2.2" data-path="definición-del-modelo-arima.html"><a href="definición-del-modelo-arima.html#modelo-holt-winter"><i class="fa fa-check"></i><b>2.2</b> Modelo Holt-Winter</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Publicado con bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Analisis Tasa de Intervencion</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="definición-del-modelo-arima" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">Capítulo: 2</span> <strong>Definición del Modelo ARIMA</strong><a href="definición-del-modelo-arima.html#definición-del-modelo-arima" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><em>COMPOSICIÓN DEL MODELO ARIMA</em></p>
<ul>
<li><p>Diferenciación no estacional (d): Dado que ya se aplicó una primera diferenciación en los datos y todavía no es completamente estacionaria, es posible considerar incrementar el parámetro de a 2.</p></li>
<li><p>Estacionalidad (seasonal): Como existe un patrón estacional claro en la serie, conviene incluir una diferenciación estacional (D = 1) y ajustar los parámetros P y Q para capturar las dependencias estacionales. Se probará el modelo con un seasonal = c(1, 1, 1) para incluir un término autoregresivo y uno de promedio móvil estacional.</p></li>
<li><p>Componentes AR y MA (p y q): Dado que p y q determinan la cantidad de términos autoregresivos y de promedio móvil, se recomienda probar con valores más altos para q (como 3) y ajustar p a 1 o 2 si observas que hay correlación en los residuos. Esto puede ayudar a mejorar la precisión del modelo y su capacidad predictiva.</p></li>
</ul>
<pre><code>## Series: differenced_data 
## ARIMA(1,2,3)(1,1,1)[12] 
## 
## Coefficients:
##           ar1      ma1      ma2     ma3     sar1     sma1
##       -0.9727  -0.7231  -0.9715  0.6948  -0.1013  -0.8826
## s.e.   0.0467   0.0637   0.0693  0.0509   0.0802   0.0548
## 
## sigma^2 = 0.1596:  log likelihood = -163.35
## AIC=340.7   AICc=341.1   BIC=366.46
## 
## Training set error measures:
##                       ME      RMSE       MAE MPE MAPE      MASE        ACF1
## Training set -0.02662351 0.3862772 0.2369913 NaN  Inf 0.6820726 -0.02211654</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<pre><code>## 
##  Ljung-Box test
## 
## data:  Residuals from ARIMA(1,2,3)(1,1,1)[12]
## Q* = 24.811, df = 18, p-value = 0.1302
## 
## Model df: 6.   Total lags used: 24</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-20-2.png" width="672" /></p>
<ul>
<li><p><strong>Parámetros no estacionales</strong></p></li>
<li><p>p = 1 (un término autoregresivo),</p></li>
<li><p>d = 2 (diferenciación de segundo orden para hacer estacionaria la serie en términos de tendencia),</p></li>
<li><p>q = 3 (tres términos de promedio móvil).</p></li>
<li><p>**parámetros estacionales*, donde:**</p></li>
<li><p>P = 1 (un término autoregresivo estacional),</p></li>
<li><p>D = 1 (diferenciación estacional),</p></li>
<li><p>Q = 1 (un término de promedio móvil estacional),</p></li>
<li><p>Los coeficientes y sus errores estándar sugieren que la mayoría de los términos son significativos (coeficientes altos en relación con sus errores estándar).</p></li>
<li><p>El test de Ljung-Box evalúa si los residuos del modelo son independientes (no correlacionados). Con un p-valor de 0.1302, se sugiere que los residuos no tienen autocorrelación significativa. Esto indica que el modelo está capturando bien la estructura de la serie.</p></li>
<li><p>Los resultados muestran que el modelo ARIMA(1,2,3)(1,1,1)[12] es probablemente adecuado para la serie.</p></li>
<li><p>El p-valor del test de Ljung-Box mayor a 0.05 indica que el modelo ha eliminado la mayoría de la autocorrelación en los residuos, lo cual es positivo.</p></li>
</ul>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="definición-del-modelo-arima.html#cb14-1" tabindex="-1"></a><span class="co"># Análisis de Residuos</span></span>
<span id="cb14-2"><a href="definición-del-modelo-arima.html#cb14-2" tabindex="-1"></a></span>
<span id="cb14-3"><a href="definición-del-modelo-arima.html#cb14-3" tabindex="-1"></a><span class="co"># Normal QQ Plot de los residuos</span></span>
<span id="cb14-4"><a href="definición-del-modelo-arima.html#cb14-4" tabindex="-1"></a>residuos_diff <span class="ot">&lt;-</span> <span class="fu">residuals</span>(modelo_arima)</span>
<span id="cb14-5"><a href="definición-del-modelo-arima.html#cb14-5" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))  <span class="co"># Asegúrate de que solo hay un gráfico en la ventana</span></span>
<span id="cb14-6"><a href="definición-del-modelo-arima.html#cb14-6" tabindex="-1"></a><span class="fu">qqnorm</span>(residuos_diff, <span class="at">main =</span> <span class="st">&quot;Normal QQ Plot de Residuos&quot;</span>)</span>
<span id="cb14-7"><a href="definición-del-modelo-arima.html#cb14-7" tabindex="-1"></a><span class="fu">qqline</span>(residuos_diff, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="definición-del-modelo-arima.html#cb15-1" tabindex="-1"></a><span class="co"># Realizar el test de normalidad de Shapiro-Wilk</span></span>
<span id="cb15-2"><a href="definición-del-modelo-arima.html#cb15-2" tabindex="-1"></a>shapiro_test <span class="ot">&lt;-</span> <span class="fu">shapiro.test</span>(residuos_diff)</span>
<span id="cb15-3"><a href="definición-del-modelo-arima.html#cb15-3" tabindex="-1"></a><span class="fu">print</span>(shapiro_test)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  residuos_diff
## W = 0.82525, p-value &lt; 2.2e-16</code></pre>
<p>Teniendo en cuenta la prueba de normalidad de Shapiro-Wilk, con un valor de 0.82525, siendo relativamente menor a 1, indica que los residuos no siguen una distribución normal.</p>
<p>En cuanto a p-value &lt; 2.2e-16, al ser una cifra tan pequeña, se confirma que los residuos no son normales.</p>
<hr />
<p>POSIBLE MODELO 2</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="definición-del-modelo-arima.html#cb17-1" tabindex="-1"></a><span class="co"># Aplicar auto.arima para determinar los parámetros adecuados, incluyendo las diferenciaciones</span></span>
<span id="cb17-2"><a href="definición-del-modelo-arima.html#cb17-2" tabindex="-1"></a>modelo_auto <span class="ot">&lt;-</span> <span class="fu">auto.arima</span>(differenced_data)</span>
<span id="cb17-3"><a href="definición-del-modelo-arima.html#cb17-3" tabindex="-1"></a><span class="fu">print</span>(modelo_auto)</span></code></pre></div>
<pre><code>## Series: differenced_data 
## ARIMA(1,1,2) 
## 
## Coefficients:
##           ar1      ma1      ma2
##       -0.5956  -0.1114  -0.4425
## s.e.   0.7747   0.7650   0.5442
## 
## sigma^2 = 0.1556:  log likelihood = -148.41
## AIC=304.82   AICc=304.95   BIC=319.71</code></pre>
<p>Teniendo en cuenta el anterior modelo, en donde se cuetan con los parámetros de autorregresivo, diferenciación y media móvil (1, 1, 2) respectivamente. Teniendo en cuenta los resultados en los coeficientes, se determina:</p>
<p><em>Autorregresivo:</em>
ar1 = -0.5956: con un valor negativo, indica que hay una relación inversa entre el valor actual de la serie y su valor anterior.
s.e. = 0.7747: al tener un resultado alto, se determina que la estimación es menos precisa.</p>
<p><em>Media Móvil:</em>
ma1 = -0.1114: indica que la predicción fue más alta al valor real en el período inmediatamente anterior, es decir, cuando t=-1, arrojando de esta forma un residuo negativo. Este residuo corresponde a la media del resultado anterior.
Lo anterior, relacionado con s.e.= 0.7650, indica que la estimación es relativamente imprecisa en comparación con el valor del coeficiente.</p>
<p>ma2 = -0.4425: este resultado tiene un valor negativo, similar a ma1; sin embargo, este resultado ocurre en el segundo error pasado (dos períodos atrás), es decir cuando t=-2.
Con s.e. = 0.5442, al ser menor que el de ma1, indica que ma2 es más precisa, aunque continúa teniendo una inexactitud sobre el valor.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="definición-del-modelo-arima.html#cb19-1" tabindex="-1"></a><span class="co"># Ajuste del modelo ARIMA</span></span>
<span id="cb19-2"><a href="definición-del-modelo-arima.html#cb19-2" tabindex="-1"></a>modelo_arima2 <span class="ot">&lt;-</span> <span class="fu">Arima</span>(differenced_data, <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">2</span>), <span class="at">seasonal =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>))</span>
<span id="cb19-3"><a href="definición-del-modelo-arima.html#cb19-3" tabindex="-1"></a><span class="fu">summary</span>(modelo_arima2)</span></code></pre></div>
<pre><code>## Series: differenced_data 
## ARIMA(1,1,2)(1,1,0)[12] 
## 
## Coefficients:
##          ar1      ma1     ma2     sar1
##       0.9274  -1.6115  0.6144  -0.4744
## s.e.  0.0393   0.0597  0.0583   0.0620
## 
## sigma^2 = 0.213:  log likelihood = -190.4
## AIC=390.8   AICc=391.01   BIC=409.22
## 
## Training set error measures:
##                      ME      RMSE       MAE MPE MAPE      MASE        ACF1
## Training set 0.04515282 0.4485344 0.2876226 NaN  Inf 0.8277919 -0.08017884</code></pre>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="definición-del-modelo-arima.html#cb21-1" tabindex="-1"></a><span class="fu">checkresiduals</span>(modelo_arima2)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<pre><code>## 
##  Ljung-Box test
## 
## data:  Residuals from ARIMA(1,1,2)(1,1,0)[12]
## Q* = 62.201, df = 20, p-value = 3.233e-06
## 
## Model df: 4.   Total lags used: 24</code></pre>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="definición-del-modelo-arima.html#cb23-1" tabindex="-1"></a><span class="co"># Pronosticar los próximos 72 períodos (6 años)</span></span>
<span id="cb23-2"><a href="definición-del-modelo-arima.html#cb23-2" tabindex="-1"></a>pronostico2 <span class="ot">&lt;-</span> <span class="fu">forecast</span>(modelo_arima2, <span class="at">h =</span> <span class="dv">72</span>)</span>
<span id="cb23-3"><a href="definición-del-modelo-arima.html#cb23-3" tabindex="-1"></a></span>
<span id="cb23-4"><a href="definición-del-modelo-arima.html#cb23-4" tabindex="-1"></a><span class="co"># Graficar el pronóstico con el eje x adecuado</span></span>
<span id="cb23-5"><a href="definición-del-modelo-arima.html#cb23-5" tabindex="-1"></a><span class="fu">plot</span>(pronostico2, <span class="at">xlab =</span> <span class="st">&quot;Año&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Tasa&quot;</span>, <span class="at">main =</span> <span class="st">&quot;Pronóstico de Tasa&quot;</span>)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-23-2.png" width="672" /></p>
<p><em>Autorregresivo:</em>
ar1 = 0.9274: Con un valor positivo, indica que existe una relación directa entre el valor actual de la serie y su valor anterior. Es decir, cuando el valor en el periodo t-1 aumenta, el valor en el periodo actual t tiende a aumentar también.</p>
<p>s.e. = 0.0393: Dado que el error estándar es bajo, indica que la estimación de este coeficiente es muy precisa. Esto sugiere que el modelo tiene una gran confianza en la relación directa entre el valor actual y el valor anterior de la serie temporal.</p>
<p><em>Media Móvil:</em>
ma1 = -1.6115: El coeficiente negativo para ma1 indica que hubo un error negativo en la predicción en el periodo inmediatamente anterior (t-1). Es decir, el modelo predijo un valor más alto que el valor real en el periodo t-1, lo que resultó en un residuo negativo. Este residuo se ajusta en el modelo a través del término de media móvil.
s.e. = 0.0597: El error estándar para ma1 es relativamente bajo, lo que sugiere que esta estimación tiene alta precisión. En otras palabras, el ajuste de la predicción actual basado en el error de la predicción del periodo anterior es bastante confiable.</p>
<p>ma2 = 0.6144: Este coeficiente positivo para ma2 indica que el error positivo en la predicción de dos periodos atrás (t-2) tiene una relación directa con el valor actual de la serie; es decir, el modelo sobreestimó el valor real dos periodos atrás, lo que resultó en un residuo positivo que ahora ajusta la predicción para el periodo actual.
s.e. = 0.0583: Al igual que el error estándar de ma1, el error estándar de ma2 es bajo, lo que indica que esta estimación es también relativamente precisa.</p>
<p><em>Autorregresivo estacional (SAR1):</em>
sar1 = -0.4744: El coeficiente negativo para sar1 sugiere que existe una relación inversa entre el valor actual de la serie y el valor de la serie con un rezago estacional de un periodo (es decir, el valor de la serie 12 periodos atrás). Si el valor de la serie en el periodo t-12 fue alto, el valor en el periodo actual t tenderá a ser más bajo.
s.e. = 0.0620: El error estándar para sar1 es relativamente bajo, lo que indica que esta estimación también es bastante precisa y que el modelo tiene una buena confianza en el impacto de la componente estacional.</p>
<p>el modelo ARIMA(1,1,2)(1,1,0) tiene coeficientes precisos para los diferentes componentes (AR, MA y SAR), lo que sugiere que el modelo está bien ajustado y que las relaciones capturadas por los coeficientes son confiables.</p>
<hr />
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="definición-del-modelo-arima.html#cb24-1" tabindex="-1"></a><span class="co"># Análisis de volatilidad utilizando fGarch</span></span>
<span id="cb24-2"><a href="definición-del-modelo-arima.html#cb24-2" tabindex="-1"></a>garch_model <span class="ot">&lt;-</span> <span class="fu">garch</span>(residuos_diff, <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span></code></pre></div>
<pre><code>## 
##  ***** ESTIMATION WITH ANALYTICAL GRADIENT ***** 
## 
## 
##      I     INITIAL X(I)        D(I)
## 
##      1     1.340879e-01     1.000e+00
##      2     5.000000e-02     1.000e+00
##      3     5.000000e-02     1.000e+00
## 
##     IT   NF      F         RELDF    PRELDF    RELDX   STPPAR   D*STEP   NPRELDF
##      0    1 -1.437e+02
##      1    3 -1.480e+02  2.86e-02  7.61e-02  3.8e-01  1.1e+03  1.0e-01  4.29e+01
##      2    4 -1.596e+02  7.30e-02  1.12e-01  2.6e-01  2.0e+00  1.0e-01  2.02e+02
##      3    6 -1.696e+02  5.86e-02  1.37e-01  3.5e-01  2.0e+00  2.7e-01  9.83e+01
##      4    7 -1.778e+02  4.64e-02  2.54e-01  2.4e-01  2.0e+00  2.7e-01  3.97e+00
##      5    9 -1.927e+02  7.71e-02  4.72e-02  2.0e-02  2.0e+00  2.7e-02  4.22e-01
##      6   11 -1.934e+02  3.51e-03  4.53e-03  2.3e-03  7.1e+00  2.7e-03  5.19e+00
##      7   12 -1.935e+02  6.17e-04  9.39e-04  1.8e-03  2.0e+00  2.7e-03  1.07e+00
##      8   16 -1.945e+02  5.36e-03  7.15e-03  5.6e-02  2.0e+00  7.2e-02  8.75e-01
##      9   17 -1.951e+02  2.97e-03  4.48e-03  5.9e-02  2.0e+00  7.2e-02  2.88e-01
##     10   18 -1.960e+02  4.50e-03  5.76e-03  5.5e-02  1.9e+00  7.2e-02  1.89e-01
##     11   19 -1.965e+02  2.57e-03  3.53e-03  5.2e-02  1.9e+00  7.2e-02  5.76e-02
##     12   21 -1.965e+02  3.32e-04  9.85e-04  2.3e-02  1.5e+00  3.3e-02  4.04e-03
##     13   22 -1.966e+02  1.11e-04  4.83e-04  2.0e-02  4.3e-02  3.3e-02  4.83e-04
##     14   23 -1.966e+02  1.72e-04  1.99e-04  1.0e-02  0.0e+00  1.4e-02  1.99e-04
##     15   24 -1.966e+02  4.62e-06  5.26e-05  7.2e-03  0.0e+00  9.6e-03  5.26e-05
##     16   25 -1.966e+02  1.45e-05  1.46e-05  3.2e-03  4.8e-01  4.8e-03  1.56e-05
##     17   26 -1.966e+02  1.82e-06  9.06e-07  9.2e-04  0.0e+00  1.3e-03  9.06e-07
##     18   36 -1.966e+02 -1.45e-15  1.41e-17  1.5e-14  2.9e+07  2.0e-14  1.21e-09
## 
##  ***** FALSE CONVERGENCE *****
## 
##  FUNCTION    -1.966092e+02   RELDX        1.527e-14
##  FUNC. EVALS      36         GRAD. EVALS      18
##  PRELDF       1.409e-17      NPRELDF      1.212e-09
## 
##      I      FINAL X(I)        D(I)          G(I)
## 
##      1    1.304269e-02     1.000e+00     1.376e-01
##      2    3.225588e-01     1.000e+00    -8.836e-03
##      3    6.542356e-01     1.000e+00    -8.460e-03</code></pre>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="definición-del-modelo-arima.html#cb26-1" tabindex="-1"></a><span class="fu">summary</span>(garch_model)</span></code></pre></div>
<pre><code>## 
## Call:
## garch(x = residuos_diff, order = c(1, 1))
## 
## Model:
## GARCH(1,1)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.7470 -0.5934 -0.1147  0.3248  5.6322 
## 
## Coefficient(s):
##     Estimate  Std. Error  t value Pr(&gt;|t|)    
## a0  0.013043    0.001689    7.721 1.15e-14 ***
## a1  0.322559    0.056827    5.676 1.38e-08 ***
## b1  0.654236    0.038567   16.964  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Diagnostic Tests:
##  Jarque Bera Test
## 
## data:  Residuals
## X-squared = 650.13, df = 2, p-value &lt; 2.2e-16
## 
## 
##  Box-Ljung test
## 
## data:  Squared.Residuals
## X-squared = 0.024148, df = 1, p-value = 0.8765</code></pre>
<p><em>Coeficiente del modelo:</em></p>
<p>a0 = 0.013043: Este valor es significativo, lo que indica que existe una volatilidad base que es constante y no depende de los errores o la volatilidad pasada.</p>
<p>a1 = 0.322559: Este coeficiente refleja el impacto de los errores pasados sobre la volatilidad actual. Un valor de a1 = 0.322559 indica que los errores pasados tienen una relación positiva moderada con la volatilidad actual. Además, este coeficiente es altamente significativo (p-value &lt; 0.001), lo que sugiere que el impacto de los errores pasados son importantes en el modelo.</p>
<p>b1 = 0.654236: Este coeficiente refleja el impacto de la volatilidad pasada sobre la volatilidad actual. Un valor de b1 = 0.654236 indica que la volatilidad pasada tiene una gran influencia en la volatilidad futura. Este coeficiente también es altamente significativo (p-value &lt; 2e-16), lo que sugiere que la persistencia de la volatilidad es fuerte.</p>
<p><em>Error estándar y significancia:</em>
Error estándar de a0 = 0.001689, a1 = 0.056827, b1 = 0.038567: Los errores estándar son relativamente bajos en comparación con los coeficientes estimados, lo que sugiere que las estimaciones de los parámetros del modelo son precisas.</p>
<p>Los valores de t y los p-values asociados a los coeficientes (a0, a1, b1) muestran que todos los coeficientes son estadísticamente significativos. Esto indica que cada uno de estos parámetros tienen un impacto significativo en la volatilidad modelada.</p>
<p><em>Resultados de los tets diagnósticos:</em></p>
<p>Jarque-Bera Test: Este test evalúa la normalidad de los residuos. El valor de X-squared = 650.13 y el p-value &lt; 2.2e-16 indican que los residuos no siguen una distribución normal.</p>
<p>Box-Ljung Test (Squared Residuals): Este test evalúa la autocorrelación en los residuos al cuadrado, lo que en este caso indica si hay dependencias en la volatilidad. El valor X-squared = 0.024148 y p-value = 0.8765 sugieren que no hay autocorrelación significativa en los residuos al cuadrado, lo que implica que el modelo GARCH(1,1) ha capturado adecuadamente la dinámica de la volatilidad y no quedan patrones significativos en los residuos.</p>
<hr />
<div id="algoritmo-de-holt-winter" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> Algoritmo de Holt Winter<a href="definición-del-modelo-arima.html#algoritmo-de-holt-winter" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Puede manejar la estacionalidad en el conjunto de datos simplemente calculando el valor central y luego sumándolo o multiplicándolo por la pendiente y la estacionalidad. Solo tenemos que asegurarnos de ajustar el conjunto correcto de parámetros, y tenemos el mejor ajuste.</p>
<p>Recuerde siempre verificar la eficiencia del modelo utilizando el valor MAPE (error porcentual absoluto medio) o el valor RMSE (error cuadrático medio), y la precisión puede depender del problema comercial y el conjunto de datos disponible para entrenar y probar el modelo.</p>
<p>Se observan la tendencia y los ciclos</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="definición-del-modelo-arima.html#cb28-1" tabindex="-1"></a><span class="co"># Graficar solo líneas</span></span>
<span id="cb28-2"><a href="definición-del-modelo-arima.html#cb28-2" tabindex="-1"></a><span class="fu">plot</span>(data2<span class="sc">$</span>Anio, data2<span class="sc">$</span>Tasa, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">main =</span> <span class="st">&quot;Grafico con Regresion&quot;</span>, <span class="at">xlab =</span> <span class="st">&quot;Anio&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Tasa&quot;</span>)</span>
<span id="cb28-3"><a href="definición-del-modelo-arima.html#cb28-3" tabindex="-1"></a></span>
<span id="cb28-4"><a href="definición-del-modelo-arima.html#cb28-4" tabindex="-1"></a><span class="co"># Ajustar el modelo de regresión lineal</span></span>
<span id="cb28-5"><a href="definición-del-modelo-arima.html#cb28-5" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(Tasa <span class="sc">~</span> Anio, <span class="at">data =</span> data2)</span>
<span id="cb28-6"><a href="definición-del-modelo-arima.html#cb28-6" tabindex="-1"></a></span>
<span id="cb28-7"><a href="definición-del-modelo-arima.html#cb28-7" tabindex="-1"></a><span class="co"># Agregar la línea de regresión al gráfico</span></span>
<span id="cb28-8"><a href="definición-del-modelo-arima.html#cb28-8" tabindex="-1"></a><span class="fu">abline</span>(modelo, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="definición-del-modelo-arima.html#cb29-1" tabindex="-1"></a><span class="co"># Graficar</span></span>
<span id="cb29-2"><a href="definición-del-modelo-arima.html#cb29-2" tabindex="-1"></a><span class="fu">ggplot</span>(data2, <span class="fu">aes</span>(<span class="at">x =</span> Mes, <span class="at">y =</span> Anio, <span class="at">fill =</span> Tasa)) <span class="sc">+</span></span>
<span id="cb29-3"><a href="definición-del-modelo-arima.html#cb29-3" tabindex="-1"></a>  <span class="fu">geom_tile</span>() <span class="sc">+</span>  <span class="co"># Usar geom_tile para crear un gráfico de calor</span></span>
<span id="cb29-4"><a href="definición-del-modelo-arima.html#cb29-4" tabindex="-1"></a>  <span class="fu">scale_fill_gradient</span>(<span class="at">low =</span> <span class="st">&quot;white&quot;</span>, <span class="at">high =</span> <span class="st">&quot;blue&quot;</span>) <span class="sc">+</span>  <span class="co"># Colores del llenado</span></span>
<span id="cb29-5"><a href="definición-del-modelo-arima.html#cb29-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Tasa por Año y Mes&quot;</span>, <span class="at">x =</span> <span class="st">&quot;Mes&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Año&quot;</span>) <span class="sc">+</span></span>
<span id="cb29-6"><a href="definición-del-modelo-arima.html#cb29-6" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="definición-del-modelo-arima.html#cb30-1" tabindex="-1"></a><span class="co"># serie_temporal &lt;- ts(data2[[&quot;Tasa&quot;]], start = c(min(data2$Anio), 1), frequency = 12)</span></span>
<span id="cb30-2"><a href="definición-del-modelo-arima.html#cb30-2" tabindex="-1"></a></span>
<span id="cb30-3"><a href="definición-del-modelo-arima.html#cb30-3" tabindex="-1"></a><span class="co"># Extraer el ciclo de la serie temporal</span></span>
<span id="cb30-4"><a href="definición-del-modelo-arima.html#cb30-4" tabindex="-1"></a>cicle <span class="ot">&lt;-</span> <span class="fu">cycle</span>(ts_data)</span>
<span id="cb30-5"><a href="definición-del-modelo-arima.html#cb30-5" tabindex="-1"></a></span>
<span id="cb30-6"><a href="definición-del-modelo-arima.html#cb30-6" tabindex="-1"></a><span class="co"># Ver los ciclos</span></span>
<span id="cb30-7"><a href="definición-del-modelo-arima.html#cb30-7" tabindex="-1"></a><span class="fu">print</span>(cicle)</span></code></pre></div>
<pre><code>##      Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec
## 1999                   5   6   7   8   9  10  11  12
## 2000   1   2   3   4   5   6   7   8   9  10  11  12
## 2001   1   2   3   4   5   6   7   8   9  10  11  12
## 2002   1   2   3   4   5   6   7   8   9  10  11  12
## 2003   1   2   3   4   5   6   7   8   9  10  11  12
## 2004   1   2   3   4   5   6   7   8   9  10  11  12
## 2005   1   2   3   4   5   6   7   8   9  10  11  12
## 2006   1   2   3   4   5   6   7   8   9  10  11  12
## 2007   1   2   3   4   5   6   7   8   9  10  11  12
## 2008   1   2   3   4   5   6   7   8   9  10  11  12
## 2009   1   2   3   4   5   6   7   8   9  10  11  12
## 2010   1   2   3   4   5   6   7   8   9  10  11  12
## 2011   1   2   3   4   5   6   7   8   9  10  11  12
## 2012   1   2   3   4   5   6   7   8   9  10  11  12
## 2013   1   2   3   4   5   6   7   8   9  10  11  12
## 2014   1   2   3   4   5   6   7   8   9  10  11  12
## 2015   1   2   3   4   5   6   7   8   9  10  11  12
## 2016   1   2   3   4   5   6   7   8   9  10  11  12
## 2017   1   2   3   4   5   6   7   8   9  10  11  12
## 2018   1   2   3   4   5   6   7   8   9  10  11  12
## 2019   1   2   3   4   5   6   7   8   9  10  11  12
## 2020   1   2   3   4   5   6   7   8   9  10  11  12
## 2021   1   2   3   4   5   6   7   8   9  10  11  12
## 2022   1   2   3   4   5   6   7   8   9  10  11  12
## 2023   1   2   3   4   5   6   7   8   9  10  11  12
## 2024   1   2   3   4   5   6   7   8   9  10  11  12</code></pre>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="definición-del-modelo-arima.html#cb32-1" tabindex="-1"></a><span class="co"># boxplot(data2~cycle(data2))</span></span>
<span id="cb32-2"><a href="definición-del-modelo-arima.html#cb32-2" tabindex="-1"></a></span>
<span id="cb32-3"><a href="definición-del-modelo-arima.html#cb32-3" tabindex="-1"></a><span class="co"># Crear el boxplot por ciclo (mes) para observar la estacionalidad</span></span>
<span id="cb32-4"><a href="definición-del-modelo-arima.html#cb32-4" tabindex="-1"></a><span class="fu">boxplot</span>(ts_data <span class="sc">~</span> <span class="fu">cycle</span>(ts_data), </span>
<span id="cb32-5"><a href="definición-del-modelo-arima.html#cb32-5" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">&quot;Mes&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Tasa&quot;</span>, </span>
<span id="cb32-6"><a href="definición-del-modelo-arima.html#cb32-6" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">&quot;Boxplot de Tasa por Mes&quot;</span>)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="definición-del-modelo-arima.html#cb33-1" tabindex="-1"></a><span class="co"># plot(log(airmiles), ylab=&#39;log(airmiles)&#39;, xlab=&#39;Anio&#39;, main=&#39;Logaritmo de la tasa&#39;)</span></span>
<span id="cb33-2"><a href="definición-del-modelo-arima.html#cb33-2" tabindex="-1"></a></span>
<span id="cb33-3"><a href="definición-del-modelo-arima.html#cb33-3" tabindex="-1"></a><span class="fu">plot</span>(data2<span class="sc">$</span>Anio, <span class="fu">log</span>(data2<span class="sc">$</span>Tasa), <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, </span>
<span id="cb33-4"><a href="definición-del-modelo-arima.html#cb33-4" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Log(Tasa)&quot;</span>, <span class="at">xlab =</span> <span class="st">&quot;Año&quot;</span>, </span>
<span id="cb33-5"><a href="definición-del-modelo-arima.html#cb33-5" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Logaritmo de la Tasa a lo largo del Tiempo&quot;</span>)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-29-1.png" width="672" /></p>
</div>
<div id="modelo-holt-winter" class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Modelo Holt-Winter<a href="definición-del-modelo-arima.html#modelo-holt-winter" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="definición-del-modelo-arima.html#cb34-1" tabindex="-1"></a><span class="co"># modelo_HW = HoltWinters(log(airmiles), seasonal = &quot;additive&quot;)</span></span>
<span id="cb34-2"><a href="definición-del-modelo-arima.html#cb34-2" tabindex="-1"></a><span class="co"># plot(modelo_HW, main = &#39;Ajuste con Holt-Winters&#39;, xlab = &#39;Anio&#39;, ylab=&#39;log(airmiles)&#39;)</span></span>
<span id="cb34-3"><a href="definición-del-modelo-arima.html#cb34-3" tabindex="-1"></a></span>
<span id="cb34-4"><a href="definición-del-modelo-arima.html#cb34-4" tabindex="-1"></a></span>
<span id="cb34-5"><a href="definición-del-modelo-arima.html#cb34-5" tabindex="-1"></a><span class="co"># Aplicar el modelo Holt-Winters a la serie temporal</span></span>
<span id="cb34-6"><a href="definición-del-modelo-arima.html#cb34-6" tabindex="-1"></a>modelo_HW <span class="ot">&lt;-</span> <span class="fu">HoltWinters</span>(ts_data)</span>
<span id="cb34-7"><a href="definición-del-modelo-arima.html#cb34-7" tabindex="-1"></a><span class="fu">print</span>(modelo_HW)</span></code></pre></div>
<pre><code>## Holt-Winters exponential smoothing with trend and additive seasonal component.
## 
## Call:
## HoltWinters(x = ts_data)
## 
## Smoothing parameters:
##  alpha: 0.9409767
##  beta : 0.2941339
##  gamma: 1
## 
## Coefficients:
##             [,1]
## a   26.078382560
## b    1.351095717
## s1   0.013514274
## s2   0.042701886
## s3  -0.084488171
## s4  -0.120823220
## s5  -0.046940131
## s6  -0.105835904
## s7  -0.176555877
## s8  -0.002083574
## s9   0.085858823
## s10  0.501395118
## s11  0.266415988
## s12 -0.078382560</code></pre>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="definición-del-modelo-arima.html#cb36-1" tabindex="-1"></a><span class="co"># Graficar el ajuste del modelo a los datos históricos</span></span>
<span id="cb36-2"><a href="definición-del-modelo-arima.html#cb36-2" tabindex="-1"></a><span class="fu">plot</span>(modelo_HW, <span class="at">main =</span> <span class="st">&quot;Ajuste del Modelo Holt-Winters&quot;</span>)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-30-1.png" width="672" /></p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="definición-del-modelo-arima.html#cb37-1" tabindex="-1"></a><span class="co"># Pronóstico con Holt-Winters para los próximos 12 meses</span></span>
<span id="cb37-2"><a href="definición-del-modelo-arima.html#cb37-2" tabindex="-1"></a>pronostico_hw <span class="ot">&lt;-</span> <span class="fu">forecast</span>(modelo_HW, <span class="at">h =</span> <span class="dv">12</span>)</span>
<span id="cb37-3"><a href="definición-del-modelo-arima.html#cb37-3" tabindex="-1"></a></span>
<span id="cb37-4"><a href="definición-del-modelo-arima.html#cb37-4" tabindex="-1"></a><span class="co"># Graficar el pronóstico</span></span>
<span id="cb37-5"><a href="definición-del-modelo-arima.html#cb37-5" tabindex="-1"></a><span class="fu">plot</span>(pronostico_hw, <span class="at">main =</span> <span class="st">&quot;Pronostico Holt-Winters para Tasa&quot;</span>)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-30-2.png" width="672" /></p>
<p><em>Parámetro suavizado:</em></p>
<p>Alpha (α = 0.9409767): Este es el parámetro de suavizado para el componente de nivel. Un valor cercano a 1, como el que está arrojando el resultado, indica que el modelo le da gran peso a los datos recientes para estimar el nivel actual de la serie. Esto significa que las observaciones recientes tienen un impacto significativo en la estimación del nivel.</p>
<p>Beta (β = 0.2941339): Este es el parámetro de suavizado para el componente de tendencia en el modelo de Holt-Winters. Un valor de β moderadamente bajo, como 0.2941339, sugiere que el modelo da un peso relativamente moderado a los cambios en la tendencia. Es decir, el modelo no es extremadamente sensible a las variaciones en la tendencia, pero sigue siendo capaz de capturarlas de manera significativa. Con este valor, el modelo ajusta la tendencia de forma más suave y gradual, lo que implica que no tiene una sobrereacción ante cambios recientes en la dirección de los datos.</p>
<p>Gamma (γ = 1): Este es el parámetro de suavizado para el componente estacional. Un valor de γ = 1 sugiere que el modelo da completo peso a los componentes estacionales previos en la serie.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="definición-del-modelo-arima.html#cb38-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">fitted</span>(modelo_HW), <span class="at">main=</span><span class="st">&#39;Descomposicion con HW&#39;</span>, <span class="at">xlab=</span><span class="st">&#39;Anio&#39;</span>, <span class="at">ylab=</span><span class="st">&#39;log(airmiles)&#39;</span>)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-31-1.png" width="672" /></p>
<p>Se predice el método Holt Winters</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="definición-del-modelo-arima.html#cb39-1" tabindex="-1"></a>pred <span class="ot">=</span> <span class="fu">predict</span>(modelo_HW, <span class="dv">4</span>, <span class="at">prediction.interval =</span> <span class="cn">TRUE</span>)</span>
<span id="cb39-2"><a href="definición-del-modelo-arima.html#cb39-2" tabindex="-1"></a>pred</span></code></pre></div>
<pre><code>##               fit      upr      lwr
## Jan 2025 27.44299 28.23593 26.65006
## Feb 2025 28.82328 30.07272 27.57383
## Mar 2025 30.04718 31.76924 28.32513
## Apr 2025 31.36194 33.58414 29.13975</code></pre>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="definición-del-modelo-arima.html#cb41-1" tabindex="-1"></a><span class="fu">plot</span>(modelo_HW, pred)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-33-1.png" width="672" /></p>
<p>```</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="enunciado.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/%s",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": false,
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
