<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo: 2 Definición de Modelos | Analisis Tasa de Intervencion</title>
  <meta name="description" content="Capítulo: 2 Definición de Modelos | Analisis Tasa de Intervencion" />
  <meta name="generator" content="bookdown 0.41 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo: 2 Definición de Modelos | Analisis Tasa de Intervencion" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo: 2 Definición de Modelos | Analisis Tasa de Intervencion" />
  
  
  

<meta name="author" content="Gabriel Orozco/Diana Aguirre/Edgard Camacho" />


<meta name="date" content="2024-10-21" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="enunciado.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Analisis Tasa de Intervencion</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="enunciado.html"><a href="enunciado.html"><i class="fa fa-check"></i><b>1</b> <strong>Enunciado</strong></a>
<ul>
<li class="chapter" data-level="1.1" data-path="enunciado.html"><a href="enunciado.html#análisis-exploratorio"><i class="fa fa-check"></i><b>1.1</b> Análisis exploratorio</a></li>
<li class="chapter" data-level="1.2" data-path="enunciado.html"><a href="enunciado.html#gráficos-de-visualización"><i class="fa fa-check"></i><b>1.2</b> Gráficos de visualización</a></li>
<li class="chapter" data-level="1.3" data-path="enunciado.html"><a href="enunciado.html#análisis-de-serie-de-tiempo"><i class="fa fa-check"></i><b>1.3</b> Análisis de serie de tiempo</a></li>
<li class="chapter" data-level="1.4" data-path="enunciado.html"><a href="enunciado.html#promedio-o-media-móvil"><i class="fa fa-check"></i><b>1.4</b> Promedio o media móvil</a></li>
<li class="chapter" data-level="1.5" data-path="enunciado.html"><a href="enunciado.html#rezago-operador-backshift-y-estacionalidad"><i class="fa fa-check"></i><b>1.5</b> Rezago (operador backshift) y estacionalidad</a></li>
<li class="chapter" data-level="1.6" data-path="enunciado.html"><a href="enunciado.html#descomposición"><i class="fa fa-check"></i><b>1.6</b> Descomposición</a></li>
<li class="chapter" data-level="1.7" data-path="enunciado.html"><a href="enunciado.html#estacionariedad"><i class="fa fa-check"></i><b>1.7</b> Estacionariedad</a></li>
<li class="chapter" data-level="1.8" data-path="enunciado.html"><a href="enunciado.html#diferenciación"><i class="fa fa-check"></i><b>1.8</b> Diferenciación</a></li>
<li class="chapter" data-level="1.9" data-path="enunciado.html"><a href="enunciado.html#volver-a-verificar-la-estacionariedad-tras-la-diferenciación"><i class="fa fa-check"></i><b>1.9</b> Volver a verificar la Estacionariedad tras la Diferenciación</a></li>
<li class="chapter" data-level="1.10" data-path="enunciado.html"><a href="enunciado.html#autocorrelación-acf-y-parcial-pacf"><i class="fa fa-check"></i><b>1.10</b> Autocorrelación (ACF) y Parcial (PACF)</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="definición-de-modelos.html"><a href="definición-de-modelos.html"><i class="fa fa-check"></i><b>2</b> <strong>Definición de Modelos</strong></a>
<ul>
<li class="chapter" data-level="2.1" data-path="definición-de-modelos.html"><a href="definición-de-modelos.html#modelo-arima"><i class="fa fa-check"></i><b>2.1</b> Modelo Arima</a></li>
<li class="chapter" data-level="2.2" data-path="definición-de-modelos.html"><a href="definición-de-modelos.html#algoritmo-de-holt-winter"><i class="fa fa-check"></i><b>2.2</b> Algoritmo de Holt Winter</a></li>
<li class="chapter" data-level="2.3" data-path="definición-de-modelos.html"><a href="definición-de-modelos.html#modelo-holt-winter"><i class="fa fa-check"></i><b>2.3</b> Modelo Holt-Winter</a></li>
<li class="chapter" data-level="2.4" data-path="definición-de-modelos.html"><a href="definición-de-modelos.html#metodología-box-jenkins"><i class="fa fa-check"></i><b>2.4</b> Metodología Box Jenkins</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Publicado con bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Analisis Tasa de Intervencion</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="definición-de-modelos" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">Capítulo: 2</span> <strong>Definición de Modelos</strong><a href="definición-de-modelos.html#definición-de-modelos" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="modelo-arima" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> Modelo Arima<a href="definición-de-modelos.html#modelo-arima" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A continuación se probarán dos alternativas de modelo ARIMA, de acuerdo con los análisis realizados previamente, a fin de elegir aquel que se acomode mejor a la serie.</p>
<p><strong>Alternativa 1 - c(1, 2, 3) (1, 1, 1):</strong></p>
<ul>
<li><p>Diferenciación no estacional (d): Dado que ya se aplicó una primera diferenciación en los datos y todavía no es completamente estacionaria, es posible considerar incrementar el parámetro de a 2.</p></li>
<li><p>Estacionalidad (seasonal): Como existe un patrón estacional claro en la serie, conviene incluir una diferenciación estacional (D = 1) y ajustar los parámetros P y Q para capturar las dependencias estacionales. Se probará el modelo con un seasonal = c(1, 1, 1) para incluir un término autoregresivo y uno de promedio móvil estacional.</p></li>
<li><p>Componentes AR y MA (p y q): Dado que p y q determinan la cantidad de términos autoregresivos y de promedio móvil, conviene probar con valores más altos para q y ajustar p de acuerdo con la correlación en los residuos. Esto puede ayudar a mejorar la precisión del modelo y su capacidad predictiva.</p></li>
</ul>
<pre><code>## Series: differenced_data 
## ARIMA(1,2,3)(1,1,1)[12] 
## 
## Coefficients:
##           ar1      ma1      ma2     ma3     sar1     sma1
##       -0.9727  -0.7231  -0.9715  0.6948  -0.1013  -0.8826
## s.e.   0.0467   0.0637   0.0693  0.0509   0.0802   0.0548
## 
## sigma^2 = 0.1596:  log likelihood = -163.35
## AIC=340.7   AICc=341.1   BIC=366.46
## 
## Training set error measures:
##                       ME      RMSE       MAE MPE MAPE      MASE        ACF1
## Training set -0.02662351 0.3862772 0.2369913 NaN  Inf 0.6820726 -0.02211654</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<pre><code>## 
##  Ljung-Box test
## 
## data:  Residuals from ARIMA(1,2,3)(1,1,1)[12]
## Q* = 24.811, df = 18, p-value = 0.1302
## 
## Model df: 6.   Total lags used: 24</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-22-2.png" width="672" /></p>
<ul>
<li><p><strong>Parámetros no estacionales</strong></p></li>
<li><p>p = 1 (un término autoregresivo),</p></li>
<li><p>d = 2 (diferenciación de segundo orden para hacer estacionaria la serie en términos de tendencia),</p></li>
<li><p>q = 3 (tres términos de promedio móvil).</p></li>
<li><p><strong>parámetros estacionales, donde:</strong></p></li>
<li><p>P = 1 (un término autoregresivo estacional),</p></li>
<li><p>D = 1 (diferenciación estacional),</p></li>
<li><p>Q = 1 (un término de promedio móvil estacional),</p></li>
<li><p>Los coeficientes y sus errores estándar sugieren que la mayoría de los términos son significativos (coeficientes altos en relación con sus errores estándar).</p></li>
<li><p>El test de Ljung-Box evalúa si los residuos del modelo son independientes (no correlacionados). Con un p-valor de 0.1302, se sugiere que los residuos no tienen autocorrelación significativa. Esto indica que el modelo está capturando bien la estructura de la serie.</p></li>
<li><p>Los resultados muestran que el modelo ARIMA(1,2,3)(1,1,1)[12] es probablemente adecuado para la serie.</p></li>
<li><p>El p-valor del test de Ljung-Box mayor a 0.05 indica que el modelo ha eliminado la mayoría de la autocorrelación en los residuos, lo cual es positivo.</p></li>
</ul>
<p><strong>Alternativa 1 - Análisis de Residuos</strong></p>
<p><img src="index_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  residuos_diff
## W = 0.82525, p-value &lt; 2.2e-16</code></pre>
<p>Teniendo en cuenta la prueba de normalidad de Shapiro-Wilk, con un valor de 0.82525, siendo relativamente menor a 1, indica que los residuos no siguen una distribución normal.</p>
<p>En cuanto a p-value &lt; 2.2e-16, al ser una cifra tan pequeña, se confirma que los residuos no son normales.</p>
<p>Por su parte, en la gráfica se evidencia un patrón en que los residuos tienen colas más gruesas que una distribución normal, lo cual reafirma la posible presencia de outliers o una distribución sesgada en los datos.</p>
<p><strong>Alternativa 1 - Análisis de volatilidad utilizando Garch</strong></p>
<pre><code>## 
##  ***** ESTIMATION WITH ANALYTICAL GRADIENT ***** 
## 
## 
##      I     INITIAL X(I)        D(I)
## 
##      1     1.340879e-01     1.000e+00
##      2     5.000000e-02     1.000e+00
##      3     5.000000e-02     1.000e+00
## 
##     IT   NF      F         RELDF    PRELDF    RELDX   STPPAR   D*STEP   NPRELDF
##      0    1 -1.437e+02
##      1    3 -1.480e+02  2.86e-02  7.61e-02  3.8e-01  1.1e+03  1.0e-01  4.29e+01
##      2    4 -1.596e+02  7.30e-02  1.12e-01  2.6e-01  2.0e+00  1.0e-01  2.02e+02
##      3    6 -1.696e+02  5.86e-02  1.37e-01  3.5e-01  2.0e+00  2.7e-01  9.83e+01
##      4    7 -1.778e+02  4.64e-02  2.54e-01  2.4e-01  2.0e+00  2.7e-01  3.97e+00
##      5    9 -1.927e+02  7.71e-02  4.72e-02  2.0e-02  2.0e+00  2.7e-02  4.22e-01
##      6   11 -1.934e+02  3.51e-03  4.53e-03  2.3e-03  7.1e+00  2.7e-03  5.19e+00
##      7   12 -1.935e+02  6.17e-04  9.39e-04  1.8e-03  2.0e+00  2.7e-03  1.07e+00
##      8   16 -1.945e+02  5.36e-03  7.15e-03  5.6e-02  2.0e+00  7.2e-02  8.75e-01
##      9   17 -1.951e+02  2.97e-03  4.48e-03  5.9e-02  2.0e+00  7.2e-02  2.88e-01
##     10   18 -1.960e+02  4.50e-03  5.76e-03  5.5e-02  1.9e+00  7.2e-02  1.89e-01
##     11   19 -1.965e+02  2.57e-03  3.53e-03  5.2e-02  1.9e+00  7.2e-02  5.76e-02
##     12   21 -1.965e+02  3.32e-04  9.85e-04  2.3e-02  1.5e+00  3.3e-02  4.04e-03
##     13   22 -1.966e+02  1.11e-04  4.83e-04  2.0e-02  4.3e-02  3.3e-02  4.83e-04
##     14   23 -1.966e+02  1.72e-04  1.99e-04  1.0e-02  0.0e+00  1.4e-02  1.99e-04
##     15   24 -1.966e+02  4.62e-06  5.26e-05  7.2e-03  0.0e+00  9.6e-03  5.26e-05
##     16   25 -1.966e+02  1.45e-05  1.46e-05  3.2e-03  4.8e-01  4.8e-03  1.56e-05
##     17   26 -1.966e+02  1.82e-06  9.06e-07  9.2e-04  0.0e+00  1.3e-03  9.06e-07
##     18   36 -1.966e+02 -1.45e-15  1.41e-17  1.5e-14  2.9e+07  2.0e-14  1.21e-09
## 
##  ***** FALSE CONVERGENCE *****
## 
##  FUNCTION    -1.966092e+02   RELDX        1.527e-14
##  FUNC. EVALS      36         GRAD. EVALS      18
##  PRELDF       1.409e-17      NPRELDF      1.212e-09
## 
##      I      FINAL X(I)        D(I)          G(I)
## 
##      1    1.304269e-02     1.000e+00     1.376e-01
##      2    3.225588e-01     1.000e+00    -8.836e-03
##      3    6.542356e-01     1.000e+00    -8.460e-03</code></pre>
<pre><code>## 
## Call:
## garch(x = residuos_diff, order = c(1, 1))
## 
## Model:
## GARCH(1,1)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.7470 -0.5934 -0.1147  0.3248  5.6322 
## 
## Coefficient(s):
##     Estimate  Std. Error  t value Pr(&gt;|t|)    
## a0  0.013043    0.001689    7.721 1.15e-14 ***
## a1  0.322559    0.056827    5.676 1.38e-08 ***
## b1  0.654236    0.038567   16.964  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Diagnostic Tests:
##  Jarque Bera Test
## 
## data:  Residuals
## X-squared = 650.13, df = 2, p-value &lt; 2.2e-16
## 
## 
##  Box-Ljung test
## 
## data:  Squared.Residuals
## X-squared = 0.024148, df = 1, p-value = 0.8765</code></pre>
<p>El modelo GARCH(1,1) parece ser adecuado para modelar la volatilidad de residuos_diff, ya que los coeficientes son significativos y el test de Box-Ljung no muestra autocorrelación en los residuos al cuadrado.</p>
<p>La alta significancia de los coeficientes ARCH (a1) y GARCH (b1) indica que tanto los residuos recientes como la volatilidad pasada influyen en la volatilidad actual.</p>
<p>La prueba de Jarque-Bera sugiere que los residuos no siguen una distribución normal, lo cual puede indicar la presencia de colas pesadas o asimetría, características típicas en series financieras.</p>
<p>Este modelo GARCH(1,1) es útil para capturar los cambios en la volatilidad de la serie residuos_diff. La ausencia de autocorrelación en los residuos al cuadrado también sugiere que el modelo ha capturado adecuadamente la heterocedasticidad de la serie.</p>
<p><strong>Auto Arima para identificar la Alternativa 2</strong></p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="definición-de-modelos.html#cb18-1" tabindex="-1"></a><span class="co"># Aplicar auto.arima para determinar los parámetros adecuados, incluyendo las diferenciaciones</span></span>
<span id="cb18-2"><a href="definición-de-modelos.html#cb18-2" tabindex="-1"></a>modelo_auto <span class="ot">&lt;-</span> <span class="fu">auto.arima</span>(differenced_data)</span>
<span id="cb18-3"><a href="definición-de-modelos.html#cb18-3" tabindex="-1"></a><span class="fu">print</span>(modelo_auto)</span></code></pre></div>
<pre><code>## Series: differenced_data 
## ARIMA(1,1,2) 
## 
## Coefficients:
##           ar1      ma1      ma2
##       -0.5956  -0.1114  -0.4425
## s.e.   0.7747   0.7650   0.5442
## 
## sigma^2 = 0.1556:  log likelihood = -148.41
## AIC=304.82   AICc=304.95   BIC=319.71</code></pre>
<p>El modelo ARIMA(1,1,2) se seleccionó como el mejor ajuste para differenced_data basado en los valores del AIC, AICc, y BIC. La inclusión de términos AR y MA sugiere que hay dependencias de corto plazo en la serie, pero el ajuste no es perfecto, dado el tamaño de los errores estándar y el valor de sigma^2. Si el objetivo es la predicción, este modelo podría ser una buena base, aunque podrían explorarse otros modelos o ajustes adicionales para mejorar la precisión.</p>
<p><strong>Alternativa 2 - c(1, 1, 2) (1, 1, 0):</strong></p>
<pre><code>## Series: differenced_data 
## ARIMA(1,1,2)(1,1,0)[12] 
## 
## Coefficients:
##          ar1      ma1     ma2     sar1
##       0.9274  -1.6115  0.6144  -0.4744
## s.e.  0.0393   0.0597  0.0583   0.0620
## 
## sigma^2 = 0.213:  log likelihood = -190.4
## AIC=390.8   AICc=391.01   BIC=409.22
## 
## Training set error measures:
##                      ME      RMSE       MAE MPE MAPE      MASE        ACF1
## Training set 0.04515282 0.4485344 0.2876226 NaN  Inf 0.8277919 -0.08017884</code></pre>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="definición-de-modelos.html#cb21-1" tabindex="-1"></a><span class="fu">checkresiduals</span>(modelo_arima2)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<pre><code>## 
##  Ljung-Box test
## 
## data:  Residuals from ARIMA(1,1,2)(1,1,0)[12]
## Q* = 62.201, df = 20, p-value = 3.233e-06
## 
## Model df: 4.   Total lags used: 24</code></pre>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="definición-de-modelos.html#cb23-1" tabindex="-1"></a><span class="co"># Pronosticar los próximos 72 períodos (6 años)</span></span>
<span id="cb23-2"><a href="definición-de-modelos.html#cb23-2" tabindex="-1"></a>pronostico2 <span class="ot">&lt;-</span> <span class="fu">forecast</span>(modelo_arima2, <span class="at">h =</span> <span class="dv">72</span>)</span></code></pre></div>
<p><em>Autorregresivo:</em>
ar1 = 0.9274: Con un valor positivo, indica que existe una relación directa entre el valor actual de la serie y su valor anterior. Es decir, cuando el valor en el periodo t-1 aumenta, el valor en el periodo actual t tiende a aumentar también.</p>
<p>s.e. = 0.0393: Dado que el error estándar es bajo, indica que la estimación de este coeficiente es muy precisa. Esto sugiere que el modelo tiene una gran confianza en la relación directa entre el valor actual y el valor anterior de la serie temporal.</p>
<p><em>Media Móvil:</em>
ma1 = -1.6115: El coeficiente negativo para ma1 indica que hubo un error negativo en la predicción en el periodo inmediatamente anterior (t-1). Es decir, el modelo predijo un valor más alto que el valor real en el periodo t-1, lo que resultó en un residuo negativo. Este residuo se ajusta en el modelo a través del término de media móvil.
s.e. = 0.0597: El error estándar para ma1 es relativamente bajo, lo que sugiere que esta estimación tiene alta precisión. En otras palabras, el ajuste de la predicción actual basado en el error de la predicción del periodo anterior es bastante confiable.</p>
<p>ma2 = 0.6144: Este coeficiente positivo para ma2 indica que el error positivo en la predicción de dos periodos atrás (t-2) tiene una relación directa con el valor actual de la serie; es decir, el modelo sobreestimó el valor real dos periodos atrás, lo que resultó en un residuo positivo que ahora ajusta la predicción para el periodo actual.
s.e. = 0.0583: Al igual que el error estándar de ma1, el error estándar de ma2 es bajo, lo que indica que esta estimación es también relativamente precisa.</p>
<p><em>Autorregresivo estacional (SAR1):</em>
sar1 = -0.4744: El coeficiente negativo para sar1 sugiere que existe una relación inversa entre el valor actual de la serie y el valor de la serie con un rezago estacional de un periodo (es decir, el valor de la serie 12 periodos atrás). Si el valor de la serie en el periodo t-12 fue alto, el valor en el periodo actual t tenderá a ser más bajo.
s.e. = 0.0620: El error estándar para sar1 es relativamente bajo, lo que indica que esta estimación también es bastante precisa y que el modelo tiene una buena confianza en el impacto de la componente estacional.</p>
<p>el modelo ARIMA(1,1,2)(1,1,0) tiene coeficientes precisos para los diferentes componentes (AR, MA y SAR), lo que sugiere que el modelo está bien ajustado y que las relaciones capturadas por los coeficientes son confiables.</p>
<p><strong>Alternativa 2 - Análisis de residuos</strong></p>
<p><img src="index_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  residuos_diff
## W = 0.82525, p-value &lt; 2.2e-16</code></pre>
<p>Los resultados del test de Shapiro-Wilk indican que los residuos (residuos_diff) no siguen una distribución normal.</p>
<p>En cuanto a la gráfica también refleja la No normalidad. La desviación de los puntos en los extremos sugiere que los residuos tienen colas más pesadas de lo que se esperaría bajo una distribución normal. Este resultado es coherente con el Shapiro-Wilk test.</p>
<p><strong>Alternativa 2 - Análisis de volatilidad fGarch</strong></p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="definición-de-modelos.html#cb25-1" tabindex="-1"></a><span class="co"># Análisis de volatilidad utilizando fGarch</span></span>
<span id="cb25-2"><a href="definición-de-modelos.html#cb25-2" tabindex="-1"></a>garch_model2 <span class="ot">&lt;-</span> <span class="fu">garch</span>(residuos_diff2, <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span></code></pre></div>
<pre><code>## 
##  ***** ESTIMATION WITH ANALYTICAL GRADIENT ***** 
## 
## 
##      I     INITIAL X(I)        D(I)
## 
##      1     1.798156e-01     1.000e+00
##      2     5.000000e-02     1.000e+00
##      3     5.000000e-02     1.000e+00
## 
##     IT   NF      F         RELDF    PRELDF    RELDX   STPPAR   D*STEP   NPRELDF
##      0    1 -9.650e+01
##      1    3 -1.042e+02  7.44e-02  7.89e-02  2.8e-01  8.2e+02  1.0e-01  3.25e+01
##      2    4 -1.111e+02  6.20e-02  1.20e-01  3.7e-01  3.4e+00  2.0e-01  4.91e+02
##      3    6 -1.192e+02  6.76e-02  6.37e-02  7.1e-02  2.6e+00  4.3e-02  3.19e+02
##      4    8 -1.201e+02  7.73e-03  1.21e-02  2.5e-02  3.9e+00  1.8e-02  2.54e+02
##      5    9 -1.209e+02  6.63e-03  7.43e-03  1.8e-02  2.0e+00  1.8e-02  1.65e+02
##      6   10 -1.231e+02  1.80e-02  1.88e-02  3.9e-02  2.0e+00  3.7e-02  1.56e+02
##      7   13 -1.333e+02  7.61e-02  1.51e-01  2.9e-01  2.0e+00  3.3e-01  1.04e+02
##      8   17 -1.350e+02  1.25e-02  3.39e-02  8.0e-03  9.6e+00  1.0e-02  4.20e+00
##      9   21 -1.361e+02  8.41e-03  1.24e-02  1.5e-01  1.9e+00  2.4e-01  2.21e-01
##     10   26 -1.362e+02  7.32e-04  1.68e-03  2.1e-03  3.1e+00  2.3e-03  2.20e-01
##     11   27 -1.362e+02  1.75e-04  1.61e-04  1.8e-03  2.0e+00  2.3e-03  1.72e-01
##     12   31 -1.365e+02  2.15e-03  4.63e-03  9.8e-02  1.9e+00  1.3e-01  1.72e-01
##     13   32 -1.369e+02  2.60e-03  3.98e-03  7.1e-02  9.1e-01  1.3e-01  8.01e-03
##     14   34 -1.371e+02  1.88e-03  2.87e-03  1.6e-02  1.3e+00  2.3e-02  5.21e-03
##     15   36 -1.372e+02  9.16e-05  1.63e-04  5.9e-03  8.2e-01  9.4e-03  2.57e-04
##     16   37 -1.372e+02  3.19e-05  1.21e-05  3.7e-03  0.0e+00  7.4e-03  1.21e-05
##     17   60 -1.372e+02  8.29e-16  1.09e-15  1.5e-14  1.7e+09  2.2e-14  6.85e-06
##     18   62 -1.372e+02 -1.04e-15  4.84e-16  6.9e-15  3.7e+09  9.8e-15  7.42e-06
## 
##  ***** FALSE CONVERGENCE *****
## 
##  FUNCTION    -1.371593e+02   RELDX        6.878e-15
##  FUNC. EVALS      62         GRAD. EVALS      18
##  PRELDF       4.843e-16      NPRELDF      7.420e-06
## 
##      I      FINAL X(I)        D(I)          G(I)
## 
##      1    1.388353e-02     1.000e+00     6.749e+00
##      2    2.667688e-01     1.000e+00    -9.784e-04
##      3    7.154210e-01     1.000e+00    -7.331e-02</code></pre>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="definición-de-modelos.html#cb27-1" tabindex="-1"></a><span class="fu">summary</span>(garch_model2)</span></code></pre></div>
<pre><code>## 
## Call:
## garch(x = residuos_diff2, order = c(1, 1))
## 
## Model:
## GARCH(1,1)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -4.13901 -0.39761  0.08921  0.55154  5.00046 
## 
## Coefficient(s):
##     Estimate  Std. Error  t value Pr(&gt;|t|)    
## a0   0.01388     0.00307    4.522 6.12e-06 ***
## a1   0.26677     0.05394    4.946 7.57e-07 ***
## b1   0.71542     0.04765   15.013  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Diagnostic Tests:
##  Jarque Bera Test
## 
## data:  Residuals
## X-squared = 262.14, df = 2, p-value &lt; 2.2e-16
## 
## 
##  Box-Ljung test
## 
## data:  Squared.Residuals
## X-squared = 0.0032557, df = 1, p-value = 0.9545</code></pre>
<ul>
<li><p>El modelo GARCH(1,1) parece capturar correctamente la volatilidad en los residuos, dado que no hay autocorrelación significativa en los residuos al cuadrado.</p></li>
<li><p>Aunque los residuos no son normales (como muestra la prueba de Jarque-Bera), el modelo es aún válido, ya que los modelos GARCH no requieren normalidad en los residuos.</p></li>
</ul>
<p>*El valor elevado de 𝑏1 (0.71542) indica una alta persistencia en la volatilidad, lo que es característico en este tipo de series de tiempo financieras.</p>
<p>En resumen, este modelo GARCH(1,1) parece adecuado para modelar la volatilidad de los residuos, aunque los residuos no sean normales.</p>
<p><strong>Comparación de modelos</strong></p>
<pre><code>## Criterios estadísticos:</code></pre>
<pre><code>## Modelo 1:</code></pre>
<pre><code>## AIC: 340.703</code></pre>
<pre><code>## BIC: 366.4642</code></pre>
<pre><code>## Modelo 2:</code></pre>
<pre><code>## AIC: 390.7992</code></pre>
<pre><code>## BIC: 409.2171</code></pre>
<pre><code>## Test de Ljung-Box para autocorrelación de residuos:</code></pre>
<pre><code>## Modelo 1:</code></pre>
<pre><code>## 
##  Box-Ljung test
## 
## data:  residuals(modelo_arima)
## X-squared = 20.709, df = 20, p-value = 0.4145</code></pre>
<pre><code>## 
## Modelo 2:</code></pre>
<pre><code>## 
##  Box-Ljung test
## 
## data:  residuals(modelo_arima2)
## X-squared = 31.586, df = 20, p-value = 0.04791</code></pre>
<pre><code>## 
## Test de normalidad Shapiro-Wilk:</code></pre>
<pre><code>## Modelo 1:</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  residuals(modelo_arima)
## W = 0.82525, p-value &lt; 2.2e-16</code></pre>
<pre><code>## 
## Modelo 2:</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  residuals(modelo_arima2)
## W = 0.88872, p-value = 3.508e-14</code></pre>
<pre><code>## 
## Métricas de error en datos de entrenamiento:</code></pre>
<pre><code>## Modelo 1:</code></pre>
<pre><code>##                       ME      RMSE       MAE MPE MAPE      MASE        ACF1
## Training set -0.02662351 0.3862772 0.2369913 NaN  Inf 0.6820726 -0.02211654</code></pre>
<pre><code>## 
## Modelo 2:</code></pre>
<pre><code>##                      ME      RMSE       MAE MPE MAPE      MASE        ACF1
## Training set 0.04515282 0.4485344 0.2876226 NaN  Inf 0.8277919 -0.08017884</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-30-1.png" width="672" /><img src="index_files/figure-html/unnamed-chunk-30-2.png" width="672" /><img src="index_files/figure-html/unnamed-chunk-30-3.png" width="672" /></p>
<p>A nivel general,</p>
<ul>
<li><p>ALTERNATIVA 1: muestra problemas de ajuste. Residuos no normales y autocorrelación presente. Aunque captura la tendencia, su precisión en los pronósticos parece más limitada.</p></li>
<li><p>ALTERNATIVA 2: ofrece un mejor ajuste. residuos más cercanos a la normalidad, sin autocorrelaciones significativas, y pronósticos con intervalos de confianza más ajustados. Esto lo hace preferible para tomar decisiones basadas en predicciones más consistentes.</p></li>
</ul>
<p>En cuanto al análisis de pronótico:</p>
<p>La Alternativa 1 (línea azul punteada) y la Alternativa 2 (línea negra continua) ofrecen pronósticos similares en cuanto a tendencia, pero ela Alternativa 2 parece ser más conservadora, con menores amplitudes en sus intervalos de confianza.</p>
<p>Los intervalos de confianza de la Alternativa 1 (zonas azules sombreadas) son más amplios, indicando mayor incertidumbre, mientras que en la 2 (zonas grises sombreadas) son más ajustados, lo que sugiere mayor precisión o menos variabilidad esperada, por tanto la 2 podría ser más confiable si se busca menor variabilidad en los pronósticos a largo plazo.</p>
<p><strong>En definitiva, </strong> la decisión es entonces optar por la Alternativa 2, ya que presenta un mejor comportamiento tanto en el ajuste a los datos como en la calidad de los pronósticos.</p>
</div>
<div id="algoritmo-de-holt-winter" class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Algoritmo de Holt Winter<a href="definición-de-modelos.html#algoritmo-de-holt-winter" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Puede manejar la estacionalidad en el conjunto de datos simplemente calculando el valor central y luego sumándolo o multiplicándolo por la pendiente y la estacionalidad. Solo tenemos que asegurarnos de ajustar el conjunto correcto de parámetros, y tenemos el mejor ajuste.</p>
<p>Recuerde siempre verificar la eficiencia del modelo utilizando el valor MAPE (error porcentual absoluto medio) o el valor RMSE (error cuadrático medio), y la precisión puede depender del problema comercial y el conjunto de datos disponible para entrenar y probar el modelo.</p>
<p>Se observan la tendencia y los ciclos:</p>
<p><img src="index_files/figure-html/unnamed-chunk-31-1.png" width="672" />
<img src="index_files/figure-html/unnamed-chunk-32-1.png" width="672" /></p>
<p>La gráfica sugiere una disminución en la tasa a lo largo del tiempo, con una estabilización en niveles bajos en los años recientes. Esto podría indicar una mejora en el fenómeno que se está midiendo con la “Tasa”, aunque el contexto específico dependerá de qué represente exactamente esa variable en el análisis.</p>
<pre><code>##      Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec
## 1999                   5   6   7   8   9  10  11  12
## 2000   1   2   3   4   5   6   7   8   9  10  11  12
## 2001   1   2   3   4   5   6   7   8   9  10  11  12
## 2002   1   2   3   4   5   6   7   8   9  10  11  12
## 2003   1   2   3   4   5   6   7   8   9  10  11  12
## 2004   1   2   3   4   5   6   7   8   9  10  11  12
## 2005   1   2   3   4   5   6   7   8   9  10  11  12
## 2006   1   2   3   4   5   6   7   8   9  10  11  12
## 2007   1   2   3   4   5   6   7   8   9  10  11  12
## 2008   1   2   3   4   5   6   7   8   9  10  11  12
## 2009   1   2   3   4   5   6   7   8   9  10  11  12
## 2010   1   2   3   4   5   6   7   8   9  10  11  12
## 2011   1   2   3   4   5   6   7   8   9  10  11  12
## 2012   1   2   3   4   5   6   7   8   9  10  11  12
## 2013   1   2   3   4   5   6   7   8   9  10  11  12
## 2014   1   2   3   4   5   6   7   8   9  10  11  12
## 2015   1   2   3   4   5   6   7   8   9  10  11  12
## 2016   1   2   3   4   5   6   7   8   9  10  11  12
## 2017   1   2   3   4   5   6   7   8   9  10  11  12
## 2018   1   2   3   4   5   6   7   8   9  10  11  12
## 2019   1   2   3   4   5   6   7   8   9  10  11  12
## 2020   1   2   3   4   5   6   7   8   9  10  11  12
## 2021   1   2   3   4   5   6   7   8   9  10  11  12
## 2022   1   2   3   4   5   6   7   8   9  10  11  12
## 2023   1   2   3   4   5   6   7   8   9  10  11  12
## 2024   1   2   3   4   5   6   7   8   9  10  11  12</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-34-1.png" width="672" /></p>
<p>Aunque hay consistencia en la mediana y el rango intercuartílico de la tasa a lo largo de los meses, existen valores atípicos en la segunda mitad del año. Esto sugiere que, aunque la tasa general se mantiene estable, en algunos meses específicos ocurren eventos o circunstancias que resultan en tasas inusualmente altas.</p>
<p><img src="index_files/figure-html/unnamed-chunk-35-1.png" width="672" /></p>
<p>La gráfica sugiere que la tasa ha sido volátil a lo largo de los años, con periodos de estabilidad relativa intercalados con cambios bruscos.</p>
<p>La caída alrededor de 2020 y el rápido aumento posterior podrían reflejar eventos económicos o circunstancias externas que afectaron la tasa en ese periodo.</p>
<p>Esto fue evidenciado en el ANÁLISIS EXPLORATORIO.</p>
</div>
<div id="modelo-holt-winter" class="section level2 hasAnchor" number="2.3">
<h2><span class="header-section-number">2.3</span> Modelo Holt-Winter<a href="definición-de-modelos.html#modelo-holt-winter" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<pre><code>## Holt-Winters exponential smoothing with trend and additive seasonal component.
## 
## Call:
## HoltWinters(x = ts_data)
## 
## Smoothing parameters:
##  alpha: 0.9409767
##  beta : 0.2941339
##  gamma: 1
## 
## Coefficients:
##             [,1]
## a   26.078382560
## b    1.351095717
## s1   0.013514274
## s2   0.042701886
## s3  -0.084488171
## s4  -0.120823220
## s5  -0.046940131
## s6  -0.105835904
## s7  -0.176555877
## s8  -0.002083574
## s9   0.085858823
## s10  0.501395118
## s11  0.266415988
## s12 -0.078382560</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-36-1.png" width="672" /><img src="index_files/figure-html/unnamed-chunk-36-2.png" width="672" /></p>
<p><em>Parámetro suavizado:</em></p>
<p>Alpha (α = 0.9409767): Este es el parámetro de suavizado para el componente de nivel. Un valor cercano a 1, como el que está arrojando el resultado, indica que el modelo le da gran peso a los datos recientes para estimar el nivel actual de la serie. Esto significa que las observaciones recientes tienen un impacto significativo en la estimación del nivel.</p>
<p>Beta (β = 0.2941339): Este es el parámetro de suavizado para el componente de tendencia en el modelo de Holt-Winters. Un valor de β moderadamente bajo, como 0.2941339, sugiere que el modelo da un peso relativamente moderado a los cambios en la tendencia. Es decir, el modelo no es extremadamente sensible a las variaciones en la tendencia, pero sigue siendo capaz de capturarlas de manera significativa. Con este valor, el modelo ajusta la tendencia de forma más suave y gradual, lo que implica que no tiene una sobrereacción ante cambios recientes en la dirección de los datos.</p>
<p>Gamma (γ = 1): Este es el parámetro de suavizado para el componente estacional. Un valor de γ = 1 sugiere que el modelo da completo peso a los componentes estacionales previos en la serie.</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="definición-de-modelos.html#cb53-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">fitted</span>(modelo_HW), <span class="at">main=</span><span class="st">&#39;Descomposicion con HW&#39;</span>, <span class="at">xlab=</span><span class="st">&#39;Anio&#39;</span>, <span class="at">ylab=</span><span class="st">&#39;log(airmiles)&#39;</span>)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-37-1.png" width="672" /></p>
<p>La tendencia ascendente en el nivel y la tendencia hacia el final del período (2025) sugiere que LA TASA está experimentando un crecimiento continuo.</p>
<p>La componente estacional muestra ciclos regulares bien definidos, lo que puede ser útil para predicciones estacionales precisas.</p>
<p>El modelo Holt-Winters parece ajustarse adecuadamente a la serie, capturando tanto las fluctuaciones estacionales como la tendencia de largo plazo.</p>
<p><strong>Se predice el método Holt Winters</strong></p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="definición-de-modelos.html#cb54-1" tabindex="-1"></a>pred <span class="ot">=</span> <span class="fu">predict</span>(modelo_HW, <span class="dv">4</span>, <span class="at">prediction.interval =</span> <span class="cn">TRUE</span>)</span>
<span id="cb54-2"><a href="definición-de-modelos.html#cb54-2" tabindex="-1"></a>pred</span></code></pre></div>
<pre><code>##               fit      upr      lwr
## Jan 2025 27.44299 28.23593 26.65006
## Feb 2025 28.82328 30.07272 27.57383
## Mar 2025 30.04718 31.76924 28.32513
## Apr 2025 31.36194 33.58414 29.13975</code></pre>
<p>Con lo anterior, se evidencia una tedencia ascendente en las predicciones para los primeros 4 meses del 2025. De igual forma, se observa un incremento en la incertidumbre a medida que van pasando los meses.</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="definición-de-modelos.html#cb56-1" tabindex="-1"></a><span class="fu">plot</span>(modelo_HW, pred)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-39-1.png" width="672" /></p>
</div>
<div id="metodología-box-jenkins" class="section level2 hasAnchor" number="2.4">
<h2><span class="header-section-number">2.4</span> Metodología Box Jenkins<a href="definición-de-modelos.html#metodología-box-jenkins" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Dentro de los pasos a seguir, tenemos</p>
<p>Visualizar la serie.
Transformarla en estacionaria.
Graficar ACF - PACF, escoger los parámetros.
Construir el modelo.
Hacer predicción.</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="definición-de-modelos.html#cb57-1" tabindex="-1"></a><span class="co">#PASOS DEL DOCUMENTO DE LA PROFE</span></span>
<span id="cb57-2"><a href="definición-de-modelos.html#cb57-2" tabindex="-1"></a></span>
<span id="cb57-3"><a href="definición-de-modelos.html#cb57-3" tabindex="-1"></a><span class="co"># Detectar punto de cambio en la media </span></span>
<span id="cb57-4"><a href="definición-de-modelos.html#cb57-4" tabindex="-1"></a>mval <span class="ot">&lt;-</span> <span class="fu">cpt.mean</span>(ts_data, <span class="at">method =</span> <span class="st">&quot;AMOC&quot;</span>)</span>
<span id="cb57-5"><a href="definición-de-modelos.html#cb57-5" tabindex="-1"></a><span class="fu">cpts</span>(mval)</span></code></pre></div>
<pre><code>## [1] 276</code></pre>
<p>Sobre la serie original se encuentran 276 puntos de cambio de media.</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="definición-de-modelos.html#cb59-1" tabindex="-1"></a><span class="co"># Graficar la serie con el punto de cambio resaltado</span></span>
<span id="cb59-2"><a href="definición-de-modelos.html#cb59-2" tabindex="-1"></a><span class="fu">plot</span>(mval, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">cpt.col =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">xlab =</span> <span class="st">&quot;Índice de Tiempo&quot;</span>, <span class="at">cpt.width =</span> <span class="dv">4</span>, </span>
<span id="cb59-3"><a href="definición-de-modelos.html#cb59-3" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Punto de Cambio en la Media&quot;</span>)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-41-1.png" width="672" /></p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="definición-de-modelos.html#cb60-1" tabindex="-1"></a><span class="fu">ndiffs</span>(ts_data)</span></code></pre></div>
<pre><code>## [1] 2</code></pre>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="definición-de-modelos.html#cb62-1" tabindex="-1"></a>differenced_data2 <span class="ot">&lt;-</span> <span class="fu">diff</span>(differenced_data)</span></code></pre></div>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="definición-de-modelos.html#cb63-1" tabindex="-1"></a><span class="co"># Detectar punto de cambio en la media </span></span>
<span id="cb63-2"><a href="definición-de-modelos.html#cb63-2" tabindex="-1"></a>mval <span class="ot">&lt;-</span> <span class="fu">cpt.mean</span>(differenced_data2, <span class="at">method =</span> <span class="st">&quot;AMOC&quot;</span>)</span>
<span id="cb63-3"><a href="definición-de-modelos.html#cb63-3" tabindex="-1"></a><span class="fu">cpts</span>(mval)</span></code></pre></div>
<pre><code>## numeric(0)</code></pre>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="definición-de-modelos.html#cb65-1" tabindex="-1"></a>mval_varios <span class="ot">&lt;-</span> <span class="fu">cpt.mean</span>(differenced_data2, <span class="at">method =</span> <span class="st">&quot;PELT&quot;</span>) <span class="co"># Detecta múltiples cambios</span></span>
<span id="cb65-2"><a href="definición-de-modelos.html#cb65-2" tabindex="-1"></a><span class="fu">cpts</span>(mval_varios)</span></code></pre></div>
<pre><code>## integer(0)</code></pre>
<p>Al correr el código sobre la serie ya diferenciada el resultado es 0, indicando que no se ha detectado ningún cambio significativo en la media de la serie.
Esto se debe a que al diferenciar la serie, se eliminan componentes como tendencia y cambios en la media, lo que puede hacer que la serie parezca más “estable” en términos de media.</p>
<p>Incluso probando el método de cambio PELT, que es más flexible y busca múltiples puntos de cambio, el resultado sobre la serie diferenciado es 0, indicando que no se detectaron puntos de cambio significativos en la media de la serie de tiempo.</p>
<pre><code>## Warning in locate.outliers.iloop(resid = resid, pars = pars, cval = cval, :
## stopped when &#39;maxit.iloop&#39; was reached
## Warning in locate.outliers.iloop(resid = resid, pars = pars, cval = cval, :
## stopped when &#39;maxit.iloop&#39; was reached
## Warning in locate.outliers.iloop(resid = resid, pars = pars, cval = cval, :
## stopped when &#39;maxit.iloop&#39; was reached</code></pre>
<pre><code>## Warning in locate.outliers.oloop(y = y, fit = fit, types = types, cval = cval,
## : stopped when &#39;maxit.oloop = 4&#39; was reached</code></pre>
<pre><code>## Series: dat.ts 
## Regression with ARIMA(1,0,1) errors 
## 
## Coefficients:
##           ar1      ma1    LS305
##       -0.0547  -0.6145  -0.8617
## s.e.   0.0940   0.0813   0.2282
## 
## sigma^2 = 0.1482:  log likelihood = -140.84
## AIC=289.68   AICc=289.81   BIC=304.57
## 
## Outliers:
##   type ind  time coefhat  tstat
## 1   LS 305 26:05 -0.8617 -3.777</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-45-1.png" width="672" /></p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="definición-de-modelos.html#cb70-1" tabindex="-1"></a><span class="co"># Ajustar un modelo lineal a la serie diferenciada o a la original si ya es estacionaria</span></span>
<span id="cb70-2"><a href="definición-de-modelos.html#cb70-2" tabindex="-1"></a>modelo_ajustado <span class="ot">&lt;-</span> <span class="fu">tslm</span>(differenced_data2 <span class="sc">~</span> trend)</span>
<span id="cb70-3"><a href="definición-de-modelos.html#cb70-3" tabindex="-1"></a><span class="fu">summary</span>(modelo_ajustado)</span></code></pre></div>
<pre><code>## 
## Call:
## tslm(formula = differenced_data2 ~ trend)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.00556 -0.00474  0.00312  0.01061  2.99455 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) -0.0121558  0.0550426  -0.221    0.825
## trend        0.0000579  0.0003108   0.186    0.852
## 
## Residual standard error: 0.4802 on 304 degrees of freedom
## Multiple R-squared:  0.0001142,  Adjusted R-squared:  -0.003175 
## F-statistic: 0.03471 on 1 and 304 DF,  p-value: 0.8523</code></pre>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="definición-de-modelos.html#cb72-1" tabindex="-1"></a><span class="co">#Graficar el modelo y los residuos para analizar el ajuste</span></span>
<span id="cb72-2"><a href="definición-de-modelos.html#cb72-2" tabindex="-1"></a><span class="fu">plot</span>(differenced_data2, <span class="at">main=</span><span class="st">&quot;Serie Diferenciada (si fue necesario) y Modelo Lineal Ajustado&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Valor&quot;</span>, <span class="at">xlab=</span><span class="st">&quot;Tiempo&quot;</span>)</span>
<span id="cb72-3"><a href="definición-de-modelos.html#cb72-3" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">fitted</span>(modelo_ajustado), <span class="at">col=</span><span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-46-1.png" width="672" /></p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="definición-de-modelos.html#cb73-1" tabindex="-1"></a><span class="co"># Análisis de residuos</span></span>
<span id="cb73-2"><a href="definición-de-modelos.html#cb73-2" tabindex="-1"></a><span class="fu">checkresiduals</span>(modelo_ajustado)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-46-2.png" width="672" /></p>
<pre><code>## 
##  Breusch-Godfrey test for serial correlation of order up to 24
## 
## data:  Residuals from Linear regression model
## LM test = 122.2, df = 24, p-value = 3.937e-15</code></pre>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="enunciado.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/%s",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": false,
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
